---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: build-publish
on:
  push:
    tags:
      - "v*"

jobs:
  run-pre-commits:
    name: Run pre-commits
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          # renovate: datasource=github-releases depName=astral-sh/uv
          version: "0.9.18"

      - name: Get secrets from vault
        id: import-secrets
        uses: hashicorp/vault-action@v3
        with:
          url: "https://vault.ednz.fr"
          method: approle
          roleId: ${{ secrets.VAULT_APPROLE_ID }}
          secretId: ${{ secrets.VAULT_APPROLE_SECRET_ID }}
          secrets: |
            kv/data/cicd/gitea container_registry_uri | GITEA_REGISTRY_ADDRESS ;
            kv/data/applications/gitea/users/actions username | GITEA_REGISTRY_USERNAME ;
            kv/data/applications/gitea/users/actions token_write | GITEA_REGISTRY_TOKEN ;

      - name: Authenticate to PyPI repository
        working-directory: ${{ github.workspace }}
        shell: bash
        run: |
          uv auth login git.ednz.fr \
            --username ${{ steps.import-secrets.outputs.GITEA_REGISTRY_USERNAME }} \
            --password ${{ steps.import-secrets.outputs.GITEA_REGISTRY_TOKEN }}

      - name: Build package
        shell: bash
        run: |
          uv build

      - name: Publish package to internal PyPI repositoriy
        shell: bash
        run: |
          uv publish --index ednz-cloud
