---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: unit-tests
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
    branches:
      - main

jobs:
  run-unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.11"
          - "3.12"
          - "3.13"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.python-version }}"

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          # renovate: datasource=github-releases depName=astral-sh/uv
          version: "0.9.18"

      - name: Install dependencies
        run: uv sync --group test

      - name: Run pytests
        run: uv run coverage run -m pytest -v -s

      - name: Run coverage report
        run: uv run coverage report -m --omit="tests/*"
